baseurl: ""
url: "http://127.0.0.1:4000"
encoding: utf-8
permalink: pretty
markdown: kramdown

kramdown:
  auto_id_stripping: true
  auto_ids: true

sass:
  sass_dir: _sass

css_dir: assets/css
js_dir: assets/js

exclude: ['README.md', 'Gemfile','Gemfile.lock','.gitignore','bernac.sublime-project', 'bernac.sublime-workspace']

collections:
- project-1
- project-2

collections:
  project-1:
    link: /project-1/
    output: true
    permalink: /project-1/:title/
  project-2:
    link: /project-2/
    output: true
    permalink: /project-2/:title/
