baseurl: ""
url: "http://127.0.0.1:4000"
encoding: utf-8
permalink: pretty
markdown: kramdown

kramdown:
  auto_id_stripping: true
  auto_ids: true

sass:
  sass_dir: _sass

assets_dir: assets
css_dir: assets/css
js_dir: assets/js
png_dir: assets/png
img_dir: assets/img

exclude: ['README.md', 'Gemfile','Gemfile.lock','.gitignore','bernac.sublime-project', 'bernac.sublime-workspace']

collections:
- 02-project
- 01-project

# can override collection links and permalinks by changing respective index permalink
# they must, however, be the same to ensure proper rendering
collections:
  01-project:
    link: /01-project/
    output: true
    permalink: /01-project/:title/
  02-project:
    link: /02-project/
    output: true
    permalink: /02-project/:title/
