baseurl: ""
url: "http://127.0.0.1:4000"
encoding: utf-8
permalink: pretty
markdown: kramdown

kramdown:
  auto_id_stripping: true
  auto_ids: true

sass:
  sass_dir: _sass

css_dir: assets/css
js_dir: assets/js
png_dir: assets/png
img_dir: assets/img

exclude: ['README.md', 'Gemfile','Gemfile.lock','.gitignore','bernac.sublime-project', 'bernac.sublime-workspace']

# can override collection links and permalinks by changing respective index permalink
# they must, however, be the same to ensure proper rendering
collections:
  20-project:
    link: /project-1/
    output: true
    permalink: /project-1/:title/
  21-project:
    link: /project-2/
    output: true
    permalink: /project-2/:title/

# Prose.io configuration
prose:
  siteurl: "https://bernacs.github.io"
  media: "/assets/img/"
