# can override collection links and permalinks by changing respective index permalink
# they must, however, be the same to ensure proper rendering
collections:
  20-fluid-sites:
    link: /stabilisation-of-fluid-sites/
    output: true
    permalink: /stabilisation-of-fluid-sites/:title/
  21-local-theories:
    link: /local-theories-of-aerodynamics/
    output: true
    permalink: /local-theories-of-aerodynamics/:title/
  22-encyclopedia:
    link: /encyclopedia/
    output: true
    permalink: /encyclopedia/:title/
  23-beautiful-thing:
    link: /a-beautiful-thing/
    output: true
    permalink: /a-beautiful-thing/:title/

baseurl: ""
url: "http://www.bernac.org"
encoding: utf-8
permalink: pretty
markdown: kramdown

kramdown:
  auto_id_stripping: true
  auto_ids: true

sass:
  sass_dir: _sass

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

css_dir: assets/css
js_dir: assets/js
png_dir: assets/png
img_dir: assets/img
graph_dir: assets/png/graph
media_dir: assets/media

lazyload:
  enabled: true
  option: lqip


js: ['navigation.min.js', 'basic.js', 'jQuery.appear.min.js', 'stickyfill.min.js', 'lazysizes.min.js']

exclude: ['README.md','Gemfile','Gemfile.lock','.gitignore','bernac.sublime-project','bernac.sublime-workspace']

tracking: UA-69836318-1

# Prose.io configuration
prose:
  siteurl: "http://www.bernac.org"
  media: "/assets/img"
  ignore:
    - index.html
    - /_layouts
    - /_includes
    - /_gitignore